Widened scope of catch statement in BrowserApplicationContext's applet init, since it's possible to get a NoClassDefFoundError, which wasn't being caught.
git-svn-id: https://svn.apache.org/repos/asf/incubator/pivot/trunk@792244 13f79535-47bb-0310-9956-ffa450edef68